on: 
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2
      - name: run the action
        id: hello
        uses: ./
        with:
          myInupt: 'narendra'
      - name: output the memory
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "total memory successfully output"
